# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: LWeEf3QNpRnw0HqLwrEm+IQQyHSv6wVwfLvjLfgQJfPeCmZFqM4kqpbZKZTzbNmrpxxT80llt3R83gIB0agEe5UVZc3ab/5zecoyVDy14ZOoSgMNAQF7TPIAAryvbN2LcezgvdPzL+jwAX+4+Vd9kxxaTvY6BI3af8j3+mgMN2uGBrznZEYVwUfG3Wg7yANAFzMO/1kg8Rykhad0CIKV58Rr8SAIeNTt+dCRCgzs9ORgJOK1Wf7epziPs1IHqVgErKlh3hEByCu9JoyQMdAukYx8we9Yk0AXrXzsEuSmnm49J/8WGjYofFd6eFGjvgRMBuIQuyqlTG93REWUn9URgxiB0AbNyXyQ7zBKvlFLKO6tPd4rrBmNBWZArEDIviuEQkBdeoTiMTDEiAqGbMjweOJPBqAe0XbkCtMLRp83A538Y6qaiiAoZ8lut1fAJ26YyhkxLwkvni7VTpvJJTzRctlwb6eH8wL1RrrjT1Zb6Wc7rUEgnooTcg3WIpyxb96vC7h/08VGjkm5PXT0RqnCCF59/LzvxHriHu/JcTzbz/twdh4S4itTc4p6x44TWVHBaqOSA1vj3z7GsTpUMpP6PFeBg4A8zNxWhdESQgExHA7Uc26n73JpkImynUihLikCDed+oxxkZR3Mt/OJ1bfsE1jBrR9brG+yuEMVt5+g0Oc=
    # SAUCE_TOKENS
    - secure: MGkqYAeM2N12JXmu1UCQ/EiolM3GzGeuCmGsF80atxDdGOhIvaKaqkuSqJDrHD0980f9HE/k7iQ+L/2h4kkG3uv78jS6fU3N7TpNdrFF5MLR14yEeilkvI0JUMljN629oafQRyxwwIKPNqCuUzaS6NZKnQ40yEUIC3zov60DQHx+uRq9pj7DHjGSAyxP59WAQqqzk0rT9we2Y3dHEL69Z8bLqJ6/ZVeeNdpRxpR9NWAoQ46IFzRz2+IN1Fos0LYsNYKB6N41uGqDmzjLe7dqJtdwBfmvYQMB80eds8Nl/eZScuqIvJ2Baml+AKqvyok/90le4ffv7AH/Vt9sWm6RD2HKyTAdNB4gRkUPuuEDHJA029y0Gz9biyVy4+RmqUJDN9lu+fzGfESkvovP5WuoYxc23dERzFipGY1PVhx0n9tEANQNzqwOlqvTLI8HhQEfFJrJU4/HcPyIjMQ1gW/Wdy8c6ZmrCOOaZc/RVqz/FH1av06+22B1Eq6wNiikc6xzMsXkMcgAjAt2Gk/WCIXQwC4lRPMbhlqbOEtMpr6Io2tqv3JtxKZxTFws3Z/mwnLh9KMjY0kWptzc3IwjfZcvbaPc5d+Kk4qLfenssEazhv8mSCRPKCWTvDacvCGrHlUOplU9t+dbFm6TjWfVSIFEf1ZyzFusc0OinoNo0v+c93g=
    - secure: hRAwREu2dfuss8prtmZGn1AHz4nh7JSXeWvDz109RSD24pG++Hka7MI42L+pT1kAE+kOf6kOCEuPy+KjQGBbL+9dCmtxtdhvfARoSDoMS7wEmzysoHGQ8s9dYrQDaCCql0wj7kxjRRTGoYDbkRh4mo6W9kaNEXEM1NFPq/r5tEsfbD9Gen6qGj/gDtaQ7WJYw+Vpj3RjiDdeDB9WzgepGLFmPOJ6MgKDJl3ZB9T0w5ZgUlADnToyInXCOqKT81kQVX0uJ9U0sQwcSuNFQSVcPhi7kG5+ar8rkQHYiY47kkkG1G8ZAeS2eM/D498LwQZ+xTTjr0LqSpvRHQmlI5QHbl32gXuR1+XRctQL7vZKWXd+hHdfwVPvhdxx23wqG7Fcgp6jG7K6GtJfeJq2scmO2U6ILIDgrIMXJYU3OXhPfw8HHBE7DMB2mVxMQFijbds/TQ4zTrxmWe2EI7MH2SCseef0yApnhDlXrbYYOTvrPieg0xKrL9AAFuv9rTXmyK7Nme9pr6WP0f0cX+U8hDHID0+uL+PgHNGGznn19mLxFg706SSj780BIU2Zc52rU5yRPTw4lMOKc8hwOQgYctEWVz9lPb3jDZYPbAQvXPhfBLUbDs5BfORo4SonO/eNg4hmCqENeH+RwpcY6kzaFXwTvee5QBNCpoADLOpkFcbBpX4=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: D86Cv/bm2YlcS2aOm0M7p99SRkcJkz1MKbh213d7Z14iekQqj+MNDVw/Wf/hsB86uPc+eSJ97B3MKp7QdA43uP7fKg4wG5aUq2gYie1XYsMn25UPdOwF2rscfYs6rmIlCnbQZ4Xuvxt/mDzRwZPkr+kZJZcbAUuJHLWFsBRdo5ujRLXSHIYoULrZGI9PTB1f/bCq7BANoU1gqCF6OQvjVp7m43/oZNApqJiXiwpRXg4AZQ/sia8/soYwom6hIby62uhR+jZUwyHYdtHhGN/lmJUER/myu/+/rB3+/YBzxrIKIgQAhbsc4pZ1/G8ndzmBUFhprWLaWRwfW8Cv759/SJRCGYNjxOv2q/EArJBpiyht+83DVfgUvlcPuxirQOFoKGHGtLCfIUoIn+CXHLG1EGBq7yy0uvsvGUpFsPLoCFFWBKCslx3lj5EsbYa7oKBgUuyV0Q0xKPuTECWf19yBz9Bt02zTR3BX68KZKMZB3EzL4nS/F3c5oiG/TNHh/opG/VGCPh9bxPPEoRgiZ4cE8vUK5/oxX4r3xm+n53qaG22uXhTWAEEwjNbmxRIS3H33HlhRpw7EMksBEDf6YJRZawJTTblH8N/YLmGi8DCX4I1glvKC7RES5YkVJU4HyIVzeoaG55VNQX1rOqnXRQJV8Afz3uYtFV4A9q5MoJy6oto=
