# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: H2kqqINJxNDL4712n+Sgz8MWR2++pVCwySZ9eddltjw81K7w0GQxDOk1Kb/C4XwonJj4DQJQjt6JvRr1BQmB8eb5slGNaIXyJ1lmBf6f6rC2lqcD+bH+H7x6C/9kn82p5KWuiYnn+b9wM2p5w8OvAc90tlRMBXJSN2iez/i9sRPK2RczQfr9OokjtV4/twPZRwOWREQcVvq5KirVhX5RGC5o2HjFDwEQsSFWV+FCvZOcjhGQ9GgyvCBrncR0Uy1IqFHcH07a7XKCPbbi/UAl8JfhAsyATQLetwBd95Um9L8gU7gBdzhk3nKikgW4j2FPZFIDJAYsiV5w76QgZBgw4IsSw7R8MMpjI8tyaBifNope2IPXobWlGrVJ8xK0ipiUd1d46lSudpc3hSqJmyK4qNrnBuVjVdYY/wuysbSupP6DPumSd5nst1/DET5/Holrj11kWrU4vMNYCaf3Ei71+RFkBtYUZvTeU9kpKHH+gnoIxewXGoT/lFyZZgwP0h8TTzZmxkYA8C1v51xE1+DcGsQfPnMr9jwvf6SQCiS2IylbarimuRK0Vc4f8WKmETJo1KRW9zsWEJHmTKlex1oi9yjcFf1njt5cTMakw2oVYr49XUAZjjFwYdOhE2BJ8fbcwXcq23dzANIyd/hgmf2N/WRWSO7YOgpCpe0Y/tPMWr8=
    # SAUCE_TOKENS
    - secure: QXyzZW3bcRJ8Lnbbw+tnMR4zqQh0H7Q4peXYHV8mq2kPwuuaaCoapNNuaHDjq3T7aSw//WwiGIu/lCIbHYyDGthhaNBEVzrM234mSalCl1dMwZhlhyeDXHUzyYr7+NkoWF7Ih2IPhw62p0Zwd9vWo73P8cdvApWq1N6cMS7yWHEFXZCBorqWdz/D2R8WzTNPYZ1aIJsUoPVW0Tm1yOl6W8LBY1p8bDFH6sOPwZFoNlY51VT6pujopxxsEvIFWuPKbweEFqeoF4QJVNGxuIw2Mbgib8Wo8RXpalvh6KsFBXCD3zIVNZX5tcz887xXSS+MIiHy0lbH23deEA2fOFUOzn/amkLYloEj1vC6JVpu4gZPzqWCoePIbNPfkvQE98icaUbfxqT5hHuNDR30Sj7ezY9sMaLtWooD9DCtUqY/kHqfAAWiFdF/TnKjWqrdiMInR+C5u/pr0NLG6Je38y6FftwHA0xO3iaE39kRRVvYaAnupTpg0bfQiqcLbc72o7jfCmNeYbX1kytLmpGaWeLXuD+6AV1HcvddN8K+XJClxCH2vpRjR0IkrzhQ4TVM7m5vgQNrQQBZZ8CB3Wa3i4zNeach/9Fc4BvZWacZsryVFoszOCpK93z+3Y+CXtpKLVrtZYm0RdBqj06CvjFaNDk53ffiQbj3buqdDw1YgVZfNws=
    - secure: vaR+iZcOiSDdysNNmG2VKuEmy1oRZDIm5nbuEmickwxavhkO8ao1r2UuqD8RN35fh19mSzrlGCd82Ocp/3h4s8yTZSnT3sDPl7SQ7iIYqs5d8QXnXNkf7kV3225ce6xZ1GAQUyK07NXFhXWSwTfkiZHe4PflYnsUiNFbwDvCbEkb5o71HQXiUEIiJqRpL80h7Z0e7L48kZnUFRcGK37FBF8GTXB2NJBp5z0G9Nw4sQtjp4YoAVP/9oLI+fFnnBkD2qVKUNnUQqJeALMGHoXxkGyP2EDYM7W0ttlbjyz/cvE1Jrh8qxlIMTGj5bG/T4cBgbCdc7GEagclFRIWRqN1RuBCqRrB2XNACsiPDPsqPyGSnoTUGbvCCJ9auh5UqW+sZrMr6gZDG/qdbmB+c1PqbKF8N6yD1txbphqWjrl+qQDZcErlGBUBpVGkt9634d1W8vkd+4k0lJ2NIixDCCxG7HVlfXDya20RUgT/AejBriBXvk78UDK3F0yc21FKERI2WWrT+kPVh6u9yR3tXUb+PggiDueeQxxydHo+k/OzLnB3FGhaS4bigMuBRs7ygXfXpIuXbkgDo71YxHOWuI2P4ifBNF4QvIuK4JSQ2TZk4teaOholMSs/ySw/2qIJFDPastrq2nmhA/9/yVIj0TIsUCKUuMQm/tHQ02N7aO8uoaM=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
  - npm install zuul --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: D86Cv/bm2YlcS2aOm0M7p99SRkcJkz1MKbh213d7Z14iekQqj+MNDVw/Wf/hsB86uPc+eSJ97B3MKp7QdA43uP7fKg4wG5aUq2gYie1XYsMn25UPdOwF2rscfYs6rmIlCnbQZ4Xuvxt/mDzRwZPkr+kZJZcbAUuJHLWFsBRdo5ujRLXSHIYoULrZGI9PTB1f/bCq7BANoU1gqCF6OQvjVp7m43/oZNApqJiXiwpRXg4AZQ/sia8/soYwom6hIby62uhR+jZUwyHYdtHhGN/lmJUER/myu/+/rB3+/YBzxrIKIgQAhbsc4pZ1/G8ndzmBUFhprWLaWRwfW8Cv759/SJRCGYNjxOv2q/EArJBpiyht+83DVfgUvlcPuxirQOFoKGHGtLCfIUoIn+CXHLG1EGBq7yy0uvsvGUpFsPLoCFFWBKCslx3lj5EsbYa7oKBgUuyV0Q0xKPuTECWf19yBz9Bt02zTR3BX68KZKMZB3EzL4nS/F3c5oiG/TNHh/opG/VGCPh9bxPPEoRgiZ4cE8vUK5/oxX4r3xm+n53qaG22uXhTWAEEwjNbmxRIS3H33HlhRpw7EMksBEDf6YJRZawJTTblH8N/YLmGi8DCX4I1glvKC7RES5YkVJU4HyIVzeoaG55VNQX1rOqnXRQJV8Afz3uYtFV4A9q5MoJy6oto=
after_deploy:
  - npm run test-cloud